# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20171227_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_trade_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
