# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 21:46
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0006_auto_20171228_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_trade_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=19),
        ),
    ]
