# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0011_remove_stock_market_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='timestamp_last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timestamp_last_updated',
        ),
    ]
