# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 22:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('last_trade_price', models.DecimalField(blank=True, decimal_places=3, max_digits=19)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('shares_owned', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=19)),
                ('last_trade_time', models.DateTimeField()),
                ('timestamp_last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
