# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_trade_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
