# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_auto_20171228_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_trade_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_trade_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
